// Generated by CoffeeScript 2.3.2
(function() {
  var aleat, jeu, res;

  aleat = function(min, max) {
    return Math.floor(min + (max - min + 1) * Math.random());
  };

  jeu = function(num) {
    var msg, saisie;
    msg = "C'est compris entre 1 et 63";
    saisie = parseInt(prompt(msg));
    if (saisie === num) {
      return "Vous avez gagné";
    } else {
      if (saisie < num) {
        alert("C'est plus");
      } else {
        alert("C'est moins");
      }
      return jeu(num);
    }
  };

  res = aleat(1, 63);

  alert(jeu(res));

}).call(this);
